#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : testfixtures
Version  : 6.14.2
Release  : 4
URL      : https://files.pythonhosted.org/packages/04/d3/ca5368a16e077e5334534532e89047c0ee56020245e83e6722f4903c47a2/testfixtures-6.14.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/04/d3/ca5368a16e077e5334534532e89047c0ee56020245e83e6722f4903c47a2/testfixtures-6.14.2.tar.gz
Summary  : A collection of helpers and mock objects for unit tests and doc tests.
Group    : Development/Tools
License  : MIT
Requires: testfixtures-license = %{version}-%{release}
Requires: testfixtures-python = %{version}-%{release}
Requires: testfixtures-python3 = %{version}-%{release}
Requires: twine
Requires: wheel
BuildRequires : buildreq-distutils3
BuildRequires : twine
BuildRequires : wheel

%description
============
        
        |CircleCI|_ |Docs|_

%package license
Summary: license components for the testfixtures package.
Group: Default

%description license
license components for the testfixtures package.


%package python
Summary: python components for the testfixtures package.
Group: Default
Requires: testfixtures-python3 = %{version}-%{release}

%description python
python components for the testfixtures package.


%package python3
Summary: python3 components for the testfixtures package.
Group: Default
Requires: python3-core
Provides: pypi(testfixtures)

%description python3
python3 components for the testfixtures package.


%prep
%setup -q -n testfixtures-6.14.2
cd %{_builddir}/testfixtures-6.14.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1599610144
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/testfixtures
cp %{_builddir}/testfixtures-6.14.2/LICENSE.txt %{buildroot}/usr/share/package-licenses/testfixtures/c33005b2cf8f05b37f5233a7b64ddad43b8f99d5
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/testfixtures/c33005b2cf8f05b37f5233a7b64ddad43b8f99d5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
